### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by samhavens** [kisstkondoros/tsmetrics-core#2]
Hi, thanks for making this. I found this from the VS Code extension.

I'm just curious, the configuration values make sense, but I was wondering if there's any documentation about why those values were chosen, and why you chose a binary system (it seems nodes either add 1 or 0 complexity).

Either way, thank you!

**Comment by kisstkondoros** [comment]
Hi, You are welcome! I'm glad that someone finds it useful ^^

>  if there's any documentation about why those values were chosen

There is no documentation at all, the idea was to get a close [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) approximation

> why you chose a binary system

It is actually not binary, the values you can see in the config are "weights", so that one can create a config which "punishes" the usage of e.g. debugger statements, continue statements etc.
